%
O9002 (FICTIONAL INTENTIONALLY PROBLEMATIC SAMPLE - NOT FOR PRODUCTION)
(SAFE START INTENTIONALLY OMITTED)
G54
M0 (RESTRICTED COMMAND)
S12500 M3 (EXCESSIVE SPINDLE SPEED)
G0 X24.5 Y0 Z-4.5 (X LIMIT VIOLATION AND SUSPICIOUS RAPID Z)
G1 X2.0 F650.0 (EXCESSIVE FEED RATE)
M5
(EXPECTED PROGRAM END INTENTIONALLY INCOMPLETE)
%

