from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ProfileFieldDefinition:
    field_key: str
    display_name: str
    category: str
    data_type: str
    allowed_units: tuple[str, ...]
    required_for_profile: bool
    safety_relevance: bool
    preferred_document_types: tuple[str, ...]
    search_terms: tuple[str, ...]
    optional_capability: bool = False
    normalization_rule: str = "preserve_source_and_normalize_known_units"
    validation_rule: str = "type_and_allowlist"
    notes: str = ""


def field(key, name, category, data_type="number", units=(), required=False,
          safety=False, sources=("machine_manual", "specification_document"),
          terms=(), optional=False, notes=""):
    return ProfileFieldDefinition(
        key, name, category, data_type, tuple(units), required, safety,
        tuple(sources), tuple(terms), optional,
        "preserve_source_and_normalize_known_units", "type_and_allowlist", notes,
    )


FIELD_REGISTRY = [
    field("manufacturer", "Manufacturer", "identity", "string", required=True,
          terms=("manufacturer", "manufactured by")),
    field("model", "Machine model", "identity", "string", required=True,
          terms=("machine model", "model")),
    field("machine_model", "Machine model (explicit)", "identity", "string", required=True,
          terms=("machine model",)),
    field("machine_series", "Machine series", "identity", "string",
          terms=("machine series", "series")),
    field("machine_variant", "Machine variant", "identity", "string",
          terms=("machine variant", "variant")),
    field("serial_number_pattern", "Serial-number pattern", "identity", "string",
          terms=("serial number", "serial-number format")),
    field("machine_type", "Machine type", "identity", "string", required=True,
          terms=("machine type", "turning center", "machining center")),
    field("controller_name", "Controller", "controller", "string", required=True,
          sources=("controller_manual", "programming_manual", "operator_manual"),
          terms=("controller name", "controller", "control system")),
    field("controller_manufacturer", "Controller manufacturer", "controller", "string",
          sources=("controller_manual", "programming_manual", "specification_document"),
          terms=("controller manufacturer",)),
    field("controller_version", "Controller version", "controller", "string",
          sources=("controller_manual", "programming_manual"),
          terms=("controller version", "software version")),
    field("controller_model", "Controller model", "controller", "string",
          sources=("controller_manual", "programming_manual"),
          terms=("controller model", "control model")),
    field("document_revision", "Document revision", "identity", "string",
          terms=("document revision", "revision")),
    field("document_publication_date", "Document publication date", "identity", "string",
          terms=("publication date", "published")),
    field("machine_units", "Machine units", "identity", "string",
          terms=("machine units", "units")),
    field("axis_count", "Axis count", "axis_limits", "integer", required=True,
          terms=("axis count", "axes")),
    field("available_axes", "Available axes", "axis_limits", "list",
          terms=("available axes", "controlled axes")),
    *[
        field(key, label, "axis_limits", units=("inch", "mm", "degrees"),
              safety=True, terms=(label.lower(), key.replace("_", " ")),
              notes="Coordinate limit; never inferred from total travel.")
        for key, label in (
            ("x_min", "X minimum"), ("x_max", "X maximum"),
            ("y_min", "Y minimum"), ("y_max", "Y maximum"),
            ("z_min", "Z minimum"), ("z_max", "Z maximum"),
            ("a_min", "A minimum"), ("a_max", "A maximum"),
            ("b_min", "B minimum"), ("b_max", "B maximum"),
            ("c_min", "C minimum"), ("c_max", "C maximum"),
        )
    ],
    field("x_travel", "X-axis travel", "axis_limits", units=("inch", "mm"),
          safety=True, terms=("x-axis travel", "x travel", "cross-slide travel",
                              "cross slide travel", "cross-slide stroke")),
    field("y_travel", "Y-axis travel", "axis_limits", units=("inch", "mm"),
          safety=True, terms=("y-axis travel", "y travel", "y stroke")),
    field("z_travel", "Z-axis travel", "axis_limits", units=("inch", "mm"),
          safety=True, terms=("z-axis travel", "z travel", "longitudinal travel",
                              "longitudinal stroke")),
    field("rotary_axis_limits", "Rotary-axis limits", "axis_limits", "object",
          units=("degrees",), safety=True, terms=("rotary axis limits", "rotary travel")),
    field("axis_home_positions", "Axis home positions", "axis_limits", "object",
          safety=True, terms=("home position", "machine home")),
    field("reference_return_behavior", "Reference-return behavior", "axis_limits", "string",
          safety=True, terms=("reference return", "zero return")),
    field("max_spindle_rpm", "Maximum spindle RPM", "spindle", units=("rpm",),
          required=True, safety=True, terms=("maximum spindle speed", "maximum spindle rpm",
                                             "max spindle rpm", "spindle speed range",
                                             "spindle speed", "spindle speeds")),
    field("min_spindle_rpm", "Minimum spindle RPM", "spindle", units=("rpm",),
          terms=("minimum spindle speed", "minimum spindle rpm",
                 "spindle speed range", "spindle speed", "spindle speeds")),
    field("max_feed_rate", "Maximum cutting feed", "feed_and_motion",
          units=("ipm", "mm/min"), required=True, safety=True,
          terms=("maximum cutting feed", "max feed rate")),
    field("rapid_traverse_rate", "Rapid traverse rate", "feed_and_motion",
          units=("ipm", "mm/min"), safety=True,
          terms=("rapid traverse", "rapid traverse speed", "rapid rate")),
    field("maximum_rapid_rate_x", "Maximum X rapid rate", "feed_and_motion",
          units=("ipm", "mm/min"), safety=True,
          terms=("x rapid rate", "x-axis rapid", "x-axis rapid traverse",
                 "rapid traverse speed (z/x-axis)", "rapid traverse speed z/x")),
    field("maximum_rapid_rate_y", "Maximum Y rapid rate", "feed_and_motion",
          units=("ipm", "mm/min"), safety=True, terms=("y rapid rate", "y-axis rapid")),
    field("maximum_rapid_rate_z", "Maximum Z rapid rate", "feed_and_motion",
          units=("ipm", "mm/min"), safety=True,
          terms=("z rapid rate", "z-axis rapid", "z-axis rapid traverse",
                 "rapid traverse speed (z/x-axis)", "rapid traverse speed z/x")),
    field("rapid_traverse_rate_x", "X-axis rapid traverse", "feed_and_motion",
          units=("ipm", "mm/min"), safety=True,
          terms=("x-axis rapid traverse", "x rapid traverse",
                 "rapid traverse speed (z/x-axis)", "rapid traverse speed z/x")),
    field("rapid_traverse_rate_z", "Z-axis rapid traverse", "feed_and_motion",
          units=("ipm", "mm/min"), safety=True,
          terms=("z-axis rapid traverse", "z rapid traverse",
                 "rapid traverse speed (z/x-axis)", "rapid traverse speed z/x")),
    field("maximum_rapid_rate_rotary", "Maximum rotary rapid rate", "feed_and_motion",
          units=("degrees/min",), safety=True, terms=("rotary rapid rate",)),
    field("feed_override_range", "Feed override range", "feed_and_motion", "string",
          terms=("feed override",)),
    field("minimum_programmable_increment", "Minimum programmable increment", "feed_and_motion",
          units=("inch", "mm"), terms=("minimum programmable increment",)),
    field("positioning_accuracy", "Positioning accuracy", "feed_and_motion",
          units=("inch", "mm"), terms=("positioning accuracy",)),
    field("repeatability", "Repeatability", "feed_and_motion",
          units=("inch", "mm"), terms=("repeatability",)),
    field("turret_station_count", "Turret stations", "tooling", "integer",
          terms=("turret stations", "station turret")),
    field("tool_capacity", "Tool capacity", "tooling", "integer",
          terms=("tool capacity", "tool changer capacity")),
    field("tool_station_count", "Tool station count", "tooling", "integer",
          terms=("tool station count", "tool-post station count", "tool post station count",
                 "tool stations", "tool post", "tool-post", "automatic tool post",
                 "positions")),
    field("turret_count", "Turret count", "tooling", "integer",
          terms=("turret count",)),
    field("maximum_tool_size", "Maximum tool size", "tooling", "string",
          terms=("maximum tool size",)),
    field("maximum_tool_weight", "Maximum tool weight", "tooling",
          units=("kg", "lb"), terms=("maximum tool weight",)),
    field("tool_change_position", "Tool-change position", "tooling", "string",
          safety=True, terms=("tool change position",)),
    field("tool_change_command", "Tool-change command", "tooling", "string",
          safety=True, terms=("tool change command",)),
    field("tool_preselection_support", "Tool preselection", "tooling", "boolean",
          terms=("tool preselection",), optional=True),
    field("tool_offset_ranges", "Tool-offset ranges", "tooling", "string",
          terms=("tool offset range",)),
    field("geometry_offset_ranges", "Geometry-offset ranges", "tooling", "string",
          terms=("geometry offset range",)),
    field("wear_offset_ranges", "Wear-offset ranges", "tooling", "string",
          terms=("wear offset range",)),
    field("tool_number_format", "Tool-number format", "tooling", "string",
          terms=("tool number format",)),
    field("tool_call_examples", "Tool-call examples", "tooling", "list",
          terms=("tool call example",), notes="Examples are not normative templates."),
    field("chuck_size", "Chuck size", "workholding", units=("inch", "mm"),
          terms=("chuck size", "chuck diameter")),
    field("maximum_bar_capacity", "Maximum bar capacity", "workholding",
          units=("inch", "mm"), terms=("bar capacity", "bar diameter")),
    field("maximum_turning_diameter", "Maximum turning diameter", "workholding",
          units=("inch", "mm"), terms=("maximum turning diameter",)),
    field("maximum_turning_length", "Maximum turning length", "workholding",
          units=("inch", "mm"), terms=("maximum turning length",)),
    field("spindle_bore", "Spindle bore", "workholding",
          units=("inch", "mm"), terms=("spindle bore", "spindle through hole")),
    field("spindle_nose", "Spindle nose", "workholding", "string",
          terms=("spindle nose",)),
    field("supported_work_offsets", "Supported work offsets", "programming", "list",
          required=True, safety=True, sources=("controller_manual", "programming_manual"),
          terms=("work offsets", "G54", "G59")),
    field("safe_start_template", "Safe-start expectations", "safety_and_setup", "string",
          required=True, safety=True, sources=("company_standard", "programming_manual"),
          terms=("safe start", "startup block")),
    field("program_end_template", "Program-ending expectations", "safety_and_setup", "string",
          required=True, safety=True, sources=("company_standard", "programming_manual"),
          terms=("program end", "ending block")),
    *[
        field(key, label, "capabilities", "boolean", terms=terms, optional=optional)
        for key, label, terms, optional in (
            ("main_spindle_present", "Main spindle", ("main spindle",), False),
            ("y_axis_present", "Y-axis capability", ("y-axis", "y axis"), True),
            ("tailstock_present", "Tailstock", ("tailstock",), True),
            ("coolant_present", "Flood coolant system", ("flood coolant system", "coolant present"), False),
            ("automatic_lubrication_present", "Automatic lubrication system",
             ("automatic lubrication system", "automatic lubrication"), False),
            ("steady_rest_support", "Steady-rest support", ("steady rest",), True),
            ("part_catcher_present", "Part catcher", ("part catcher",), True),
            ("bar_feeder_support", "Bar-feeder support", ("bar feeder",), True),
            ("spindle_orientation_support", "Spindle orientation", ("spindle orientation",), True),
            ("constant_surface_speed_support", "Constant surface speed", ("constant surface speed",), False),
            ("rotary_table_present", "Rotary table", ("rotary table",), True),
            ("fourth_axis_support", "Fourth-axis support", ("fourth axis", "4th axis"), True),
            ("fifth_axis_support", "Fifth-axis support", ("fifth axis", "5th axis"), True),
            ("through_spindle_coolant", "Through-spindle coolant", ("through-spindle coolant",), True),
            ("probe_support", "Probe support", ("probe support", "probing"), True),
            ("pallet_changer_present", "Pallet changer", ("pallet changer",), True),
        )
    ],
    field("live_tooling_present", "Live tooling", "capabilities", "boolean",
          terms=("live tooling", "driven tools"), optional=True),
    field("sub_spindle_present", "Sub-spindle", "capabilities", "boolean",
          terms=("sub-spindle", "sub spindle"), optional=True),
    field("c_axis_present", "C-axis capability", "capabilities", "boolean",
          terms=("c-axis", "c axis"), optional=True),
    field("spindle_torque", "Spindle torque", "spindle", units=("N·m", "lb-ft"),
          terms=("spindle torque",)),
    field("maximum_live_tool_rpm", "Maximum live-tool RPM", "spindle", units=("rpm",),
          terms=("maximum live tool rpm", "live tool speed")),
    field("spindle_power", "Spindle power", "spindle", units=("kW", "hp"),
          terms=("spindle power", "spindle motor", "spindle motor power",
                 "standard spindle motor power", "optional spindle motor power")),
    field("spindle_direction_support", "Spindle-direction support", "spindle", "list",
          terms=("spindle direction",)),
    field("maximum_css_value", "Maximum CSS value", "spindle",
          terms=("maximum css", "constant surface speed maximum")),
    field("spindle_override_range", "Spindle override range", "spindle", "string",
          terms=("spindle override",)),
    field("table_size", "Table size", "machine_geometry", "string",
          units=("inch", "mm"), terms=("table size",)),
    field("table_load_capacity", "Table load capacity", "machine_geometry",
          units=("kg", "lb"), terms=("table load",)),
    field("vertical_or_horizontal", "Vertical or horizontal", "machine_geometry", "string",
          terms=("vertical machining", "horizontal machining")),
    field("maximum_tool_diameter", "Maximum tool diameter", "tooling",
          units=("inch", "mm"), terms=("maximum tool diameter",)),
    field("maximum_tool_length", "Maximum tool length", "tooling",
          units=("inch", "mm"), terms=("maximum tool length",)),
    field("spindle_taper", "Spindle taper", "tooling", "string",
          terms=("spindle taper",)),
    field("net_weight", "Net weight", "machine_geometry", units=("kg", "lb"),
          terms=("net weight",)),
    field("gross_weight", "Gross weight", "machine_geometry", units=("kg", "lb"),
          terms=("gross weight",)),
    field("overall_dimensions", "Overall dimensions", "machine_geometry", "object",
          units=("inch", "mm"),
          terms=("overall dimensions", "overall dimension", "overall length",
                 "overall width", "overall height")),
    field("tool_holder_standard", "Tool-holder standard", "tooling", "string",
          terms=("tool holder standard", "toolholder standard")),
    *[
        field(key, label, "programming", "string", safety=safety,
              sources=("controller_manual", "programming_manual", "company_standard"),
              terms=terms)
        for key, label, terms, safety in (
            ("extended_work_offsets", "Extended work offsets", ("extended work offsets", "G54.1"), True),
            ("machine_coordinate_command", "Machine-coordinate command", ("machine coordinate", "G53"), True),
            ("local_coordinate_support", "Local-coordinate support", ("local coordinate", "G52"), False),
            ("coordinate_rotation_support", "Coordinate rotation", ("coordinate rotation", "G68"), False),
            ("scaling_support", "Scaling support", ("scaling", "G51"), False),
            ("polar_coordinate_support", "Polar-coordinate support", ("polar coordinate",), False),
            ("programmable_data_input_support", "Programmable data input", ("programmable data input", "G10"), False),
            ("reference_return_commands", "Reference-return commands", ("reference return", "G28"), True),
            ("absolute_positioning_command", "Absolute-positioning command", ("absolute positioning", "G90"), True),
            ("incremental_positioning_command", "Incremental-positioning command", ("incremental positioning", "G91"), True),
            ("inch_units_command", "Inch-units command", ("inch input", "G20"), True),
            ("metric_units_command", "Metric-units command", ("metric input", "G21"), True),
        )
    ],
    *[
        field(key, label, "post_processing", "list",
              sources=("controller_manual", "programming_manual", "company_standard", "approved_program"),
              terms=terms, notes="Discovered commands remain informational until explicitly reviewed.")
        for key, label, terms in (
            ("supported_g_codes", "Supported G-codes", ("g-code list", "supported g codes")),
            ("supported_m_codes", "Supported M-codes", ("m-code list", "supported m codes")),
            ("unsupported_g_codes", "Unsupported G-codes", ("unsupported g codes",)),
            ("unsupported_m_codes", "Unsupported M-codes", ("unsupported m codes",)),
            ("optional_g_codes", "Optional G-codes", ("optional g codes",)),
            ("optional_m_codes", "Optional M-codes", ("optional m codes",)),
            ("machine_builder_m_codes", "Machine-builder M-codes", ("builder m codes",)),
            ("macro_commands", "Macro commands", ("macro commands",)),
            ("canned_cycles", "Canned cycles", ("canned cycles",)),
            ("threading_cycles", "Threading cycles", ("threading cycles",)),
            ("turning_cycles", "Turning cycles", ("turning cycles",)),
            ("drilling_cycles", "Drilling cycles", ("drilling cycles",)),
            ("probing_cycles", "Probing cycles", ("probing cycles",)),
        )
    ],
    *[
        field(key, label, "safety_and_setup", "string", safety=True,
              sources=("company_standard", "programming_manual", "post_processor_document"),
              terms=terms, notes="Classify normative requirements separately from examples.")
        for key, label, terms in (
            ("safe_start_commands", "Safe-start commands", ("safe start commands",)),
            ("program_number_format", "Program-number format", ("program number format",)),
            ("sequence_number_format", "Sequence-number format", ("sequence number format",)),
            ("tool_change_template", "Tool-change template", ("tool change template",)),
            ("spindle_start_template", "Spindle-start template", ("spindle start template",)),
            ("coolant_start_template", "Coolant-start template", ("coolant start template",)),
            ("work_offset_template", "Work-offset template", ("work offset template",)),
            ("reference_return_template", "Reference-return template", ("reference return template",)),
            ("optional_stop_behavior", "Optional-stop behavior", ("optional stop",)),
            ("block_delete_behavior", "Block-delete behavior", ("block delete",)),
            ("comment_format", "Comment format", ("comment format",)),
            ("subprogram_format", "Subprogram format", ("subprogram format",)),
            ("macro_call_format", "Macro-call format", ("macro call format",)),
        )
    ],
]

FIELD_MAP = {value.field_key: value for value in FIELD_REGISTRY}
