import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { api } from "../api/client";
import { ActionMenu } from "../components/ActionMenu";
import type { AssembledPostDraft, GPostDraft, MachineProfile, PostBuilderEvidence, PostBuilderProviderStatus, PostRuleDraft, PostSectionCompare, PostSectionDraft, PostSectionKey, PostSectionReadiness, SourceDocument } from "../types";

const order: PostSectionKey[] = ["program_structure", "tooling", "spindle", "coolant", "feed", "motion", "coordinates", "cycles", "program_end"];
const eligibleTypes = new Set(["machine_manual", "controller_manual", "programming_manual", "specification_document", "post_processor_document", "company_standard", "parameter_list", "machine_configuration_document"]);
const overallLabels: Record<string, string> = { setup: "Setup", building: "Building", needs_information: "Needs Information", ready_for_review: "Ready for Review", reviewed_rnd_draft: "Reviewed R&D Draft", archived: "Archived" };
const stateLabels: Record<string, string> = { reviewed: "Reviewed", needs_review: "Drafted — Needs Review", needs_information: "Needs Information", not_started: "Not Started", deferred: "Deferred", ready: "Ready to Draft", ready_with_review: "Ready to Draft", blocked: "Unavailable" };

export function PostBuilderWorkspacePage() {
  const id = Number(useParams().draftId); const location = useLocation(); const navigate = useNavigate();
  const parts = location.pathname.replace(new RegExp(`^/gpost/${id}/?`), "").split("/").filter(Boolean);
  const view = parts[0] === "machine-knowledge" ? "knowledge" : parts[0] === "review" ? "review" : parts[0] === "versions" ? "versions" : parts[0] === "sources" || parts[0] === "evidence" ? "sources" : parts[0] === "technical" ? "technical" : parts[0] === "builder" || parts[0] === "post-builder" ? "builder" : "overview";
  const routeSection = view === "builder" && parts[1] ? parts[1] as PostSectionKey : null; const knowledgeSection = view === "knowledge" && parts[1] ? parts[1] as PostSectionKey : null;
  const [draft, setDraft] = useState<GPostDraft | null>(null); const [machine, setMachine] = useState<MachineProfile | null>(null);
  const [documents, setDocuments] = useState<SourceDocument[]>([]); const [versions, setVersions] = useState<GPostDraft[]>([]); const [provider, setProvider] = useState<PostBuilderProviderStatus | null>(null);
  const [readiness, setReadiness] = useState<PostSectionReadiness[]>([]); const [assembled, setAssembled] = useState<AssembledPostDraft | null>(null); const [sectionDrafts, setSectionDrafts] = useState<PostSectionDraft[]>([]);
  const [current, setCurrent] = useState<PostSectionDraft | null>(null); const [sectionVersions, setSectionVersions] = useState<PostSectionDraft[]>([]); const [comparison, setComparison] = useState<PostSectionCompare | null>(null);
  const [evidence, setEvidence] = useState<PostBuilderEvidence[]>([]); const [selectedEvidence, setSelectedEvidence] = useState<Set<number>>(new Set()); const [contextOpen, setContextOpen] = useState(false);
  const [reviewer, setReviewer] = useState("Local Post Engineer"); const [reason, setReason] = useState(""); const [editRule, setEditRule] = useState<number | null>(null); const [editTemplate, setEditTemplate] = useState("");
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [renameOpen, setRenameOpen] = useState(false); const [nextName, setNextName] = useState(""); const [deleteOpen, setDeleteOpen] = useState(false);

  async function load() {
    try {
      const nextDraft = await api.getGPostDraft(id); const profiles = await api.listProfiles();
      const [docs, history, nextProvider, nextReadiness, nextSections, nextAssembly] = await Promise.all([api.listDocuments(nextDraft.machine_profile_id), api.listGPostVersions(id), api.getPostBuilderProviderStatus(), api.getPostSectionReadiness(id), api.listPostSections(id), api.getAssembledPost(id)]);
      setDraft(nextDraft); setMachine(profiles.find((item) => item.id === nextDraft.machine_profile_id) ?? null); setDocuments(docs); setVersions(history); setProvider(nextProvider); setReadiness(nextReadiness); setSectionDrafts(nextSections); setAssembled(nextAssembly); setNextName(nextDraft.name);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load post workspace."); }
  }
  useEffect(() => { void load(); }, [id]);
  useEffect(() => {
    if (!routeSection) { setCurrent(null); setEvidence([]); return; }
    setBusy("evidence"); Promise.all([api.retrievePostBuilderEvidence(id, routeSection), api.listPostSectionVersions(id, routeSection)]).then(([rows, history]) => { setEvidence(rows); setSelectedEvidence(new Set(rows.map((item) => item.evidence_id))); setSectionVersions(history); setCurrent(history[0] ?? null); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load component." )).finally(() => setBusy(""));
  }, [id, routeSection]);

  const readyByKey = useMemo(() => Object.fromEntries(readiness.map((item) => [item.section_key, item])), [readiness]);
  const latestByKey = useMemo(() => { const result: Partial<Record<PostSectionKey, PostSectionDraft>> = {}; sectionDrafts.forEach((item) => { if (!result[item.section_key] || item.section_version > result[item.section_key]!.section_version) result[item.section_key] = item; }); return result; }, [sectionDrafts]);
  const componentByKey = useMemo(() => Object.fromEntries((assembled?.components ?? []).map((item) => [item.section_key, item])), [assembled]);

  async function generate() { if (!routeSection || !contextOpen) return; setBusy("generate"); setError(""); try { const created = await api.generatePostSection(id, routeSection, [...selectedEvidence], current ? "same" : "refresh"); setCurrent(created); await load(); setSectionVersions(await api.listPostSectionVersions(id, routeSection)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Component drafting failed."); } finally { setBusy(""); } }
  async function reviewRule(rule: PostRuleDraft, action: "accept" | "edit-accept" | "reject" | "needs-information") { if (!routeSection) return; setBusy(`rule-${rule.id}`); try { await api.reviewPostRule(id, routeSection, rule.id, action, { reviewer_label: reviewer.trim(), reason: reason || null, edited_template: action === "edit-accept" ? editTemplate : null }); setCurrent(await api.getPostSection(id, routeSection)); setEditRule(null); setReason(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Rule review failed."); } finally { setBusy(""); } }
  async function toggleDocument(document: SourceDocument) { setBusy(`document-${document.id}`); try { await api.setDocumentPostBuilderPolicy(document.id, !document.ai_post_builder_allowed, reviewer); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Source policy update failed."); } finally { setBusy(""); } }
  async function createVersion() { setBusy("version"); try { const created = await api.createGPostVersion(id); navigate(`/gpost/${created.id}/versions`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Version creation failed."); } finally { setBusy(""); } }
  async function rename() { if (!nextName.trim()) return; await api.updateGPostDraft(id, { name: nextName.trim() }); setRenameOpen(false); await load(); }
  async function archive() { await api.archiveGPostDraft(id); navigate("/gpost"); }
  async function remove() { try { await api.deleteGPostDraft(id); navigate("/gpost"); } catch (cause) { setError(cause instanceof Error ? cause.message : "This post cannot be deleted. Archive it instead."); setDeleteOpen(false); } }

  if (!draft || !machine || !assembled) return <section className="page">{error ? <p className="form-error">{error}</p> : <p>Loading post configuration…</p>}</section>;
  const base = `/gpost/${id}`; const reviewed = assembled.counts.reviewed ?? 0; const drafted = reviewed + (assembled.counts.needs_review ?? 0); const knownFacts = readiness.flatMap((item) => item.known_machine_facts).filter((item) => item.status === "known").length;
  const issues = assembled.components.filter((item) => item.state === "needs_information" || item.state === "needs_review");
  const activeKnowledge = knowledgeSection ? readyByKey[knowledgeSection] : null;

  return <section className="page post-builder-workspace v1-post-workspace">
    <header className="post-builder-header"><div><Link to="/gpost">← Post Builder</Link><h1>{draft.name}</h1><p>{machine.name} · {machine.controller_model || machine.controller_name} · <span className={`post-status ${assembled.status}`}>{overallLabels[assembled.status]}</span></p></div><div className="workspace-actions"><span className="saved-state">Saved</span><ActionMenu label="Export Review Package" items={[{ label: "Markdown Review", onSelect: () => window.location.assign(api.gpostExportUrl(id, "markdown")) }, { label: "R&D JSON", onSelect: () => window.location.assign(api.gpostExportUrl(id, "json")) }]} /><ActionMenu label="More" items={[{ label: "Create Version", onSelect: () => void createVersion() }, { label: "Rename Post", onSelect: () => setRenameOpen(true) }, { label: "Archive Post", onSelect: () => void archive() }, { label: "Delete Post", danger: true, divider: true, onSelect: () => setDeleteOpen(true) }]} /></div></header>
    <aside className="compact-governance"><strong>AI ASSISTS POST DEVELOPMENT ONLY</strong><span>CL/NCL, part geometry, toolpaths, and production programs are excluded from AI context.</span><Link to={`${base}/technical`}>Learn More</Link></aside>
    <nav className="post-builder-tabs" aria-label="Post Builder workflow"><Link className={view === "overview" ? "active" : ""} to={base}>Overview</Link><Link className={view === "knowledge" ? "active" : ""} to={`${base}/machine-knowledge`}>Machine Knowledge</Link><Link className={view === "builder" ? "active" : ""} to={`${base}/builder`}>Build Post</Link><Link className={view === "review" ? "active" : ""} to={`${base}/review`}>Review</Link><Link className={view === "versions" ? "active" : ""} to={`${base}/versions`}>Versions</Link><Link className={view === "sources" ? "active" : ""} to={`${base}/sources`}>Sources</Link><ActionMenu label="Technical Details" active={view === "technical"} items={[{ label: "Configuration & AI boundary", to: `${base}/technical` }, { label: "Legacy local validation", to: `${base}/advanced/legacy-preview` }]} /></nav>
    {error && <p className="form-error" role="alert">{error}</p>}

    {view === "overview" && <div className="post-overview-layout"><section className="panel post-progress"><span className="eyebrow">Post Build Progress</span><h2>{draft.name}</h2><p><strong>{drafted} of 9</strong> configuration areas drafted</p><progress value={drafted} max={9} aria-label="Post build progress" /><dl><div><dt>Reviewed</dt><dd>{reviewed}</dd></div><div><dt>Needs Review</dt><dd>{assembled.counts.needs_review ?? 0}</dd></div><div><dt>Needs Information</dt><dd>{assembled.counts.needs_information ?? 0}</dd></div><div><dt>Deferred</dt><dd>{assembled.counts.deferred ?? 0}</dd></div></dl><Link className="button primary" to={`${base}/builder`}>Continue Building</Link></section><div className="overview-secondary"><section className="panel"><h2>Needs Attention</h2>{issues.length ? issues.slice(0, 4).map((item) => <Link key={item.section_key} to={`${base}/builder/${item.section_key}`}><strong>{item.label}</strong><span>{item.missing_information[0] || stateLabels[item.state]}</span></Link>) : <p>No outstanding component issues.</p>}<Link className="button secondary" to={`${base}/review`}>Resolve Issues</Link></section><section className="panel"><h2>Source Knowledge</h2><dl><div><dt>Confirmed machine facts</dt><dd>{knownFacts}</dd></div><div><dt>Documents</dt><dd>{documents.length}</dd></div><div><dt>AI-eligible sources</dt><dd>{documents.filter((item) => item.ai_post_builder_allowed).length}</dd></div></dl><Link className="button secondary" to={`${base}/sources`}>Review Sources</Link></section></div><ProviderStrip provider={provider} /></div>}

    {view === "knowledge" && !knowledgeSection && <section className="knowledge-checklist"><header><h2>Machine Knowledge</h2><p>Compact readiness for the configuration areas that make up this post.</p></header><div className="panel table-wrap"><table><thead><tr><th>Configuration Area</th><th>Knowledge</th><th>Evidence</th><th>Status</th><th>Action</th></tr></thead><tbody>{order.map((key) => { const item = readyByKey[key]; const known = item?.known_machine_facts.filter((fact) => fact.status === "known").length ?? 0; const total = item?.known_machine_facts.length ?? 0; const status = key === "cycles" ? "Deferred" : item?.draft_allowed ? "Ready" : item?.ai_drafting_readiness === "needs_information" && item.manual_setup_readiness === "ready" ? "Needs Evidence" : "Needs Information"; return <tr key={key}><td><strong>{item?.label}</strong></td><td>{known === total ? `${known} facts` : `${known}/${total} facts`}</td><td>{item?.evidence_count ?? 0} sources</td><td><span className={`post-status ${status.toLowerCase().replaceAll(" ", "_")}`}>{status}</span></td><td><Link className="button tertiary" to={`${base}/machine-knowledge/${key}`}>{status === "Needs Information" ? "Fix" : "Review"}</Link></td></tr>; })}</tbody></table></div></section>}
    {view === "knowledge" && knowledgeSection && activeKnowledge && <section className="knowledge-detail"><Link to={`${base}/machine-knowledge`}>← Machine Knowledge</Link><h2>{activeKnowledge.label} Knowledge</h2><div className="panel">{activeKnowledge.known_machine_facts.map((fact) => <dl className="knowledge-fact" key={fact.key}><dt>{fact.label}</dt><dd>{Array.isArray(fact.value) ? fact.value.join(", ") : String(fact.value ?? "Unknown")}</dd><dd>{fact.status === "known" ? "Confirmed" : "Needs Information"}</dd></dl>)}<h3>Evidence</h3><p>{activeKnowledge.evidence_count} eligible machine sources</p><footer><button className="button secondary">Enter Value</button><Link className="button secondary" to="/documents">Find in Documents</Link><Link className="button secondary" to={`/machine-assistant?machine=${machine.id}`}>Ask Machine Assistant</Link></footer></div></section>}

    {view === "builder" && !routeSection && <section className="build-post"><header><h2>Build Post Configuration</h2><p>Build and review the machine-level behavior that makes up this one post.</p></header><AssemblySummary assembled={assembled} /><div className="post-component-grid">{order.map((key) => { const component = componentByKey[key]; const ready = readyByKey[key]; const latest = latestByKey[key]; const state = component?.state ?? "not_started"; const known = ready?.known_machine_facts.filter((fact) => fact.status === "known").length ?? 0; const total = ready?.known_machine_facts.length ?? 0; const label = state !== "not_started" ? stateLabels[state] : ready?.draft_allowed ? "Ready to Draft" : key === "cycles" ? "Deferred" : ready?.ai_drafting_readiness === "needs_information" && ready.manual_setup_readiness === "ready" ? "Needs Evidence" : "Needs Information"; const action = state === "reviewed" ? "Open" : state === "needs_review" ? "Review Draft" : key === "cycles" ? "View" : ready?.draft_allowed ? "Draft with AI" : "Resolve Information"; return <article className="panel post-component" key={key}><header><h3>{ready?.label}</h3><span className={`post-status ${state}`}>{label}{label === "Ready to Draft" && <span title="Sufficient approved machine knowledge and evidence exists for AI to propose machine-level rules. This is not approval or production readiness."> ⓘ</span>}</span></header><p>{known} of {total} machine facts known</p>{component?.missing_information[0] && <small>Missing: {component.missing_information[0]}</small>}{latest && <small>{latest.rules.length} proposed rules</small>}<Link className={`button ${action === "Draft with AI" ? "primary" : "secondary"}`} to={`${base}/builder/${key}`}>{action}</Link></article>; })}</div></section>}

    {view === "builder" && routeSection && readyByKey[routeSection] && <ComponentWorkspace base={base} section={routeSection} readiness={readyByKey[routeSection]} provider={provider} evidence={evidence} selected={selectedEvidence} setSelected={setSelectedEvidence} contextOpen={contextOpen} setContextOpen={setContextOpen} busy={busy} generate={generate} current={current} reviewer={reviewer} setReviewer={setReviewer} reason={reason} setReason={setReason} editRule={editRule} setEditRule={setEditRule} editTemplate={editTemplate} setEditTemplate={setEditTemplate} reviewRule={reviewRule} sectionVersions={sectionVersions} comparison={comparison} compare={async () => { if (sectionVersions.length > 1) setComparison(await api.comparePostSectionVersions(id, routeSection, sectionVersions[1].section_version, sectionVersions[0].section_version)); }} />}

    {view === "review" && <section className="assembled-review"><header><h2>Post Review</h2><p>Review actionable components, then inspect the complete assembled R&amp;D post configuration.</p></header>{!(assembled.counts.needs_review ?? 0) && !reviewed ? <div className="panel empty-state"><h3>No post components are ready for review.</h3><p>Build at least one post component to begin engineering review.</p><Link className="button primary" to={`${base}/builder`}>Go to Build Post</Link></div> : <><section className="panel"><h3>{assembled.counts.needs_review ?? 0} areas ready for review</h3>{assembled.components.filter((item) => item.state === "needs_review").map((item) => <div className="review-row" key={item.section_key}><div><strong>{item.label}</strong><span>{item.rules.length} proposed rules</span></div><Link className="button primary" to={`${base}/builder/${item.section_key}`}>Review</Link></div>)}{reviewed > 0 && <p><strong>Reviewed:</strong> {assembled.components.filter((item) => item.state === "reviewed").map((item) => item.label).join(", ")}</p>}</section><CompletePost assembled={assembled} machine={machine} foundation={draft.controller_family.replaceAll("_", " ")} /></>}</section>}

    {view === "versions" && <section className="post-versions"><header><div><h2>Versions</h2><p>Only versions in this logical post lineage appear here. Historical versions are read-only.</p></div><button className="button primary" disabled={busy === "version"} onClick={() => void createVersion()}>Create Version <span title="Capture the current reviewed post configuration as a new read-only version.">ⓘ</span></button></header>{!versions.length ? <div className="panel empty-state"><h3>No saved versions yet.</h3></div> : <div className="panel table-wrap"><table><thead><tr><th>Version</th><th>Status</th><th>Created</th><th>Created By</th><th>Changes</th><th>Action</th></tr></thead><tbody>{versions.map((item, index) => <tr key={item.id}><td>v{item.version}</td><td>{item.id === draft.id ? "Current" : "Historical"}</td><td>{new Date(item.created_at).toLocaleDateString()}</td><td>Local Engineer</td><td>{index === versions.length - 1 ? "Initial configuration" : "Post configuration updated"}</td><td><Link className="button tertiary" to={`/gpost/${item.id}`}>{item.id === draft.id ? "Open" : "View"}</Link></td></tr>)}</tbody></table></div>}</section>}

    {view === "sources" && <section className="post-sources"><header><h2>Post Builder Sources</h2><p>Only machine-level sources explicitly enabled here may enter Post Builder AI context. CL/NCL and production program content remain prohibited.</p></header>{!documents.length ? <div className="panel empty-state"><h3>No AI-eligible machine sources.</h3><Link className="button primary" to="/documents">Add Machine Documents</Link></div> : documents.map((document) => { const eligible = eligibleTypes.has(document.document_type); return <article className="panel source-row" key={document.id}><div><strong>{document.title}</strong><small>{document.document_type.replaceAll("_", " ")} · {document.page_count ?? "—"} pages</small></div><div><span>Post Builder AI</span><strong>{!eligible ? "Ineligible" : document.ai_post_builder_allowed ? "Allowed" : "Not Allowed"}</strong></div><Link className="button tertiary" to={`/documents/${document.id}`}>View</Link><button className="button secondary" disabled={!eligible || busy === `document-${document.id}`} onClick={() => void toggleDocument(document)}>{document.ai_post_builder_allowed ? "Disable" : "Enable"}</button>{!eligible && <aside><strong>This source cannot be used with Post Builder AI.</strong><span>Its classification is not an approved machine-level AI source. Review document classification and AI eligibility.</span></aside>}</article>; })}</section>}

    {view === "technical" && <section className="panel technical-details"><h2>Technical Details</h2><dl><div><dt>Machine Profile Revision</dt><dd>#{draft.machine_profile_revision_id} · snapshotted</dd></div><div><dt>Post Foundation</dt><dd>{draft.controller_family.replaceAll("_", " ")}</dd></div><div><dt>Provider</dt><dd>{provider?.provider ?? "disabled"}</dd></div><div><dt>External Processing</dt><dd>{provider?.external_processing ? "Enabled" : "Disabled"}</dd></div><div><dt>CL/NCL AI Access</dt><dd>Prohibited</dd></div><div><dt>Native G-POST Export</dt><dd>Not configured · future adapter</dd></div><div><dt>Legacy reference programs</dt><dd>{draft.reference_program_ids_json.length} retained for local validation</dd></div></dl></section>}

    {renameOpen && <Dialog title="Rename Post" close={() => setRenameOpen(false)}><label>Post Name<input value={nextName} onChange={(event) => setNextName(event.target.value)} /></label><button className="button primary" onClick={() => void rename()}>Save Name</button></Dialog>}
    {deleteOpen && <Dialog title={`Delete “${draft.name}”?`} close={() => setDeleteOpen(false)}><p>This removes the active R&amp;D draft. Immutable version history may require archiving instead.</p><button className="button danger" onClick={() => void remove()}>Delete Post</button></Dialog>}
  </section>;
}

function ProviderStrip({ provider }: { provider: PostBuilderProviderStatus | null }) { return <aside className="provider-strip"><span><b>AI Assistance</b> {provider?.provider.replaceAll("_", " ") ?? "Unavailable"}</span><span><b>External Processing</b> {provider?.external_processing ? "Enabled" : "Disabled"}</span><span><b>CL/NCL</b> Prohibited</span></aside>; }

function AssemblySummary({ assembled }: { assembled: AssembledPostDraft }) { return <section className="panel assembly-summary"><div><span className="eyebrow">Complete Post Configuration</span><h3>{overallLabels[assembled.status]}</h3></div><dl><div><dt>Required Areas</dt><dd>{assembled.required_area_count}</dd></div><div><dt>Reviewed</dt><dd>{assembled.counts.reviewed ?? 0}</dd></div><div><dt>Needs Review</dt><dd>{assembled.counts.needs_review ?? 0}</dd></div><div><dt>Not Started</dt><dd>{assembled.counts.not_started ?? 0}</dd></div><div><dt>Needs Information</dt><dd>{assembled.counts.needs_information ?? 0}</dd></div><div><dt>Deferred</dt><dd>Cycles</dd></div></dl><p>Components are assembled deterministically into one post. There is no whole-post AI generation.</p></section>; }

function CompletePost({ assembled, machine, foundation }: { assembled: AssembledPostDraft; machine: MachineProfile; foundation: string }) { return <section className="complete-post panel"><header><div><span className="eyebrow">Complete Post</span><h3>{assembled.name}</h3><p>{machine.name} · {foundation}</p></div><span className={`post-status ${assembled.status}`}>{overallLabels[assembled.status]}</span></header>{assembled.components.map((component) => <details key={component.section_key} open={component.state === "reviewed" || component.state === "needs_review"}><summary>{component.label}<span>{stateLabels[component.state]}</span></summary>{component.rules.length ? component.rules.map((rule) => <div className="assembled-rule" key={rule.rule_key}><strong>{rule.name}</strong><code>{rule.template}</code><small>{rule.status.replaceAll("_", " ")}</small></div>) : <p>No reviewed configuration rules yet.</p>}</details>)}</section>; }

function ComponentWorkspace({ base, section, readiness, provider, evidence, selected, setSelected, contextOpen, setContextOpen, busy, generate, current, reviewer, setReviewer, reason, setReason, editRule, setEditRule, editTemplate, setEditTemplate, reviewRule, sectionVersions, comparison, compare }: { base: string; section: PostSectionKey; readiness: PostSectionReadiness; provider: PostBuilderProviderStatus | null; evidence: PostBuilderEvidence[]; selected: Set<number>; setSelected: (value: Set<number>) => void; contextOpen: boolean; setContextOpen: (value: boolean) => void; busy: string; generate: () => Promise<void>; current: PostSectionDraft | null; reviewer: string; setReviewer: (value: string) => void; reason: string; setReason: (value: string) => void; editRule: number | null; setEditRule: (value: number | null) => void; editTemplate: string; setEditTemplate: (value: string) => void; reviewRule: (rule: PostRuleDraft, action: "accept" | "edit-accept" | "reject" | "needs-information") => Promise<void>; sectionVersions: PostSectionDraft[]; comparison: PostSectionCompare | null; compare: () => Promise<void> }) {
  return <section className="section-workspace"><header><div><Link to={`${base}/builder`}>← Build Post</Link><h2>{readiness.label}</h2><p>This configuration area contributes to one complete post.</p></div><ProviderStrip provider={provider} /></header><div className="section-workspace-grid"><section className="panel"><h3>Machine Knowledge</h3>{readiness.known_machine_facts.map((fact) => <div className="fact-row" key={fact.key}><span>{fact.label}</span><strong>{Array.isArray(fact.value) ? fact.value.join(", ") : String(fact.value ?? "Unknown")}</strong><small>{fact.status === "known" ? "Confirmed" : "Needs Information"}</small></div>)}</section><section className="panel"><h3>Eligible Evidence</h3>{busy === "evidence" && <p>Retrieving local evidence…</p>}{evidence.map((item) => <article className="evidence-choice" key={item.evidence_id}><label><input type="checkbox" checked={selected.has(item.evidence_id)} onChange={(event) => { const next = new Set(selected); event.target.checked ? next.add(item.evidence_id) : next.delete(item.evidence_id); setSelected(next); }} />Include in AI Context</label><strong>{item.document_title}</strong><small>p.{item.page_start ?? "—"}</small><p>{item.excerpt}</p><Link to={`/documents/${item.document_id}`}>View Source</Link></article>)}</section><section className="panel section-ai-action"><h3>Draft This Component</h3><button className="button secondary" onClick={() => setContextOpen(!contextOpen)}>Review AI Context</button>{contextOpen && <div className="ai-context-preview"><h4>AI Context Preview</h4><p>{readiness.known_machine_facts.filter((item) => item.status === "known").length} machine facts · {selected.size} excerpts</p><dl><div><dt>CL/NCL</dt><dd>NOT INCLUDED</dd></div><div><dt>Part Geometry</dt><dd>NOT INCLUDED</dd></div><div><dt>Production Programs</dt><dd>NOT INCLUDED</dd></div></dl></div>}<button className="button primary" disabled={!contextOpen || !readiness.draft_allowed || busy === "generate" || section === "cycles" || provider?.provider === "disabled"} onClick={() => void generate()}>{current ? "Regenerate Component Draft" : "Draft with AI"}</button>{!readiness.draft_allowed && <p className="variant-warning">Resolve missing knowledge or evidence before drafting.</p>}</section></div>{current && <GeneratedSection section={current} reviewer={reviewer} setReviewer={setReviewer} reason={reason} setReason={setReason} busy={busy} editRule={editRule} setEditRule={setEditRule} editTemplate={editTemplate} setEditTemplate={setEditTemplate} reviewRule={reviewRule} />}{sectionVersions.length > 1 && <section className="panel section-comparison"><h3>Internal Component Revisions</h3><button className="button tertiary" onClick={() => void compare()}>Compare Latest</button>{comparison && <p>Rules added: {comparison.rules_added.join(", ") || "None"} · Templates changed: {comparison.templates_changed.join(", ") || "None"}</p>}</section>}</section>;
}

function GeneratedSection({ section, reviewer, setReviewer, reason, setReason, busy, editRule, setEditRule, editTemplate, setEditTemplate, reviewRule }: { section: PostSectionDraft; reviewer: string; setReviewer: (value: string) => void; reason: string; setReason: (value: string) => void; busy: string; editRule: number | null; setEditRule: (value: number | null) => void; editTemplate: string; setEditTemplate: (value: string) => void; reviewRule: (rule: PostRuleDraft, action: "accept" | "edit-accept" | "reject" | "needs-information") => Promise<void> }) { return <section className="generated-section panel"><header><div><h3>Component Draft {section.section_version}</h3><p>{section.rules.length} proposed machine-level rules · engineer review required</p></div><span className="post-status needs_review">{stateLabels[section.status] ?? section.status.replaceAll("_", " ")}</span></header><div className="reviewer-fields"><label>Reviewer<input value={reviewer} onChange={(event) => setReviewer(event.target.value)} /></label><label>Review reason / missing information<input value={reason} onChange={(event) => setReason(event.target.value)} /></label></div>{section.rules.map((rule) => <article className="post-rule-draft" key={rule.id}><div><h4>{rule.name}</h4><p>{rule.condition}</p><code>{rule.engineer_template || rule.ai_draft_template || rule.output_behavior}</code><small>Status: {rule.status.replaceAll("_", " ")}</small>{editRule === rule.id && <label>Engineer-edited template<input value={editTemplate} onChange={(event) => setEditTemplate(event.target.value)} /></label>}</div><div><button className="button secondary" disabled={busy === `rule-${rule.id}`} onClick={() => void reviewRule(rule, "accept")}>Accept</button><button className="button secondary" onClick={() => { setEditRule(rule.id); setEditTemplate(rule.engineer_template || rule.ai_draft_template || rule.output_behavior); }}>Edit &amp; Accept</button>{editRule === rule.id && <button className="button primary" onClick={() => void reviewRule(rule, "edit-accept")}>Save Edit</button>}<button className="button secondary" onClick={() => void reviewRule(rule, "needs-information")}>Needs Information</button><button className="button danger" onClick={() => void reviewRule(rule, "reject")}>Reject</button></div></article>)}</section>; }

function Dialog({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="confirmation-backdrop"><section className="confirmation-dialog" role="dialog" aria-modal="true" aria-label={title}><h2>{title}</h2>{children}<footer><button className="button secondary" onClick={close}>Cancel</button></footer></section></div>; }
