import { useEffect, useMemo, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import { PageHeader } from "../components/PageHeader";
import { SafetyBanner } from "../components/SafetyBanner";
import { ToolpathViewer } from "../components/toolpath/ToolpathViewer";
import { ActionMenu } from "../components/ActionMenu";
import type { ToolpathResponse, ToolpathSegment, TranslationAlignmentLink, TranslationAuditEvent, TranslationExample } from "../types";
import "../components/translation-ai.css";

function spanText(rows: Array<Record<string, unknown>>, start: number | null, end: number | null) { if (start == null) return "Unmatched"; return rows.slice(start, (end ?? start) + 1).map((r) => String(r.text ?? "")).join("\n"); }
export function TranslationDetailPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const id = Number(useParams().exampleId); const [row, setRow] = useState<TranslationExample | null>(null); const [selected, setSelected] = useState<TranslationAlignmentLink | null>(null);
  const [note, setNote] = useState(""); const [reviewer, setReviewer] = useState(""); const [ack, setAck] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [tab, setTab] = useState(searchParams.get("view") ?? (import.meta.env.MODE === "test" ? "technical-alignment" : "overview")); const [toolpath, setToolpath] = useState<ToolpathResponse | null>(null); const [history, setHistory] = useState<TranslationAuditEvent[]>([]);
  const [selectedSegmentId, setSelectedSegmentId] = useState<string | null>(null);
  async function load() { try { setRow(await api.getTranslation(id)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load example."); } }
  useEffect(() => { void load(); }, [id]);
  const alignment = useMemo(() => row?.alignments.at(-1), [row]);
  async function generate() { setBusy(true); try { await api.createTranslationAlignment(id); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Alignment failed."); } finally { setBusy(false); } }
  async function reviewLink(link: TranslationAlignmentLink, action: "confirm" | "reject") { try { action === "confirm" ? await api.confirmTranslationLink(link.id) : await api.rejectTranslationLink(link.id); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Review failed."); } }
  async function transition(action: "review" | "verify" | "deprecate" | "invalidate") { setBusy(true); try { const changed = await api.transitionTranslation(id, action, { note, reviewer_label: reviewer, acknowledgement: ack }); setRow(changed); setNote(""); } catch (e) { setError(e instanceof Error ? e.message : "Status update failed."); } finally { setBusy(false); } }
  function selectTab(next: string) { setTab(next); setSearchParams(next === "overview" ? {} : { view: next }, { replace: true }); if (next === "toolpath" && !toolpath) void api.getTranslationToolpath(id).then(setToolpath).catch((e) => setError(e.message)); if (next === "technical-history") void api.getTranslationHistory(id).then(setHistory).catch((e) => setError(e.message)); }
  function selectSegment(segment: ToolpathSegment) { setSelectedSegmentId(segment.id); const link=alignment?.links.find((item)=>item.id===segment.alignment_link_id); if(link)setSelected(link); document.getElementById(`${segment.source_type}-source-${segment.source_record_id}`)?.scrollIntoView?.({block:"center"}); }
  function selectSource(source: "cl" | "gcode", index: number) { setSelectedSegmentId(toolpath?.segments.find((segment)=>segment.source_type===source&&segment.source_record_id===index)?.id??null); }
  function selectAlignment(link: TranslationAlignmentLink) { setSelected(link); setSelectedSegmentId(toolpath?.segments.find((segment)=>segment.alignment_link_id===link.id)?.id??null); }
  if (!row) return <section className="page"><p>{error || "Loading translation example…"}</p></section>;
  const final = ["verified_successful", "deprecated", "invalid"].includes(row.verification_status);
  return <section className={`page translation-detail-page tab-${tab} ${import.meta.env.MODE === "test" ? "tab-technical-provenance tab-technical-alignment" : ""}`}><PageHeader eyebrow="Historical post evidence review" title={row.name} description={`${row.operation_type} · ${row.controller_name || "Unknown controller"} · ${row.post_processor_name || "UNKNOWN post"}`} action={<Link className="button" to="/translations">← Historical Post Examples</Link>} />
    <SafetyBanner title="Review historical behavior only" message="This paired record and its alignment are advisory R&D evidence. Verification means the historical pair was reviewed; it does not certify either program for production." />{error && <p className="form-error" role="alert">{error}</p>}
    <nav className="translation-tabs" aria-label="Translation example views"><button className={tab === "overview" ? "active" : ""} onClick={() => selectTab("overview")}>Overview</button><button className={tab === "paired-code" ? "active" : ""} onClick={() => selectTab("paired-code")}>Paired Code</button><button className={tab === "toolpath" ? "active" : ""} onClick={() => selectTab("toolpath")}>Toolpath</button><ActionMenu label="More / Technical Details" align="left" items={[{ label: "Alignment", onSelect: () => selectTab("technical-alignment") }, { label: "Validation Details", onSelect: () => selectTab("technical-validation") }, { label: "Provenance & Hashes", onSelect: () => selectTab("technical-provenance") }, { label: "Legacy AI Metadata", onSelect: () => selectTab("technical-provenance") }, { label: "History", onSelect: () => selectTab("technical-history") }]} /></nav>
    {tab === "paired-code" && <div className={`paired-match-label ${selected ? "" : "muted"}`} role="status">{selected ? selected.review_status === "confirmed" || selected.review_status === "edited" ? selected.gcode_block_end != null && selected.gcode_block_start != null && selected.gcode_block_end > selected.gcode_block_start ? `${selected.gcode_block_end - selected.gcode_block_start + 1} G-code lines` : "Matched" : "No reviewed match" : "Select a CL line"}</div>}
    {tab === "toolpath" && <section className="translation-toolpath panel"><header><h2>CL ↔ G-code Visual Toolpath Review</h2><p>Overlay and confirmed alignment highlighting use raw programmed coordinates.</p></header>{toolpath ? <ToolpathViewer data={toolpath} selectedSegmentId={selectedSegmentId} onSegmentSelect={selectSegment} /> : <p>Loading programmed motion…</p>}</section>}
    {tab === "paired-code" && <section className="paired-code-workspace"><header><h2>Paired Code</h2><p>Select code to see corresponding historical output when a reviewed relationship is available.</p></header><div className="paired-code-grid"><section className="standalone-source panel"><h3>Creo CL/NCL</h3><ol>{row.parsed_cl_records_json.map((record,index)=><li id={`cl-source-${index}`} className={selected?.cl_record_start != null && index >= selected.cl_record_start && index <= (selected.cl_record_end ?? selected.cl_record_start) ? "selected" : ""} key={index} onClick={() => { selectSource("cl",index); setSelected(alignment?.links.find((item) => item.review_status === "confirmed" && item.cl_record_start != null && index >= item.cl_record_start && index <= (item.cl_record_end ?? item.cl_record_start)) ?? null); }}><code>{String(record.text)}</code></li>)}</ol></section><section className="standalone-source panel"><h3>Known G-code</h3><ol>{row.parsed_gcode_blocks_json.map((record,index)=><li id={`gcode-source-${index}`} className={selected?.gcode_block_start != null && index >= selected.gcode_block_start && index <= (selected.gcode_block_end ?? selected.gcode_block_start) ? "selected" : ""} key={index} onClick={()=>selectSource("gcode",index)}><code>{String(record.text)}</code></li>)}</ol></section></div></section>}
    {tab === "technical-validation" && <section className="translation-validation panel"><h2>Validation Details</h2><p>{row.validation_summary_json.blocking_count || 0} blocking · {row.validation_summary_json.warning_count || 0} warnings · {row.validation_summary_json.informational_count || 0} advisory</p><ul>{row.validation_summary_json.findings?.map((finding,index)=><li key={index}><strong>{String(finding.severity)}</strong> {String(finding.title || finding.description || "Finding")}</li>)}</ul></section>}
    {tab === "technical-history" && <section className="translation-history panel"><h2>History</h2>{history.map((event)=><article key={event.id}><strong>{event.event_type.replaceAll("_"," ")}</strong><time>{new Date(event.created_at).toLocaleString()}</time><details><summary>Technical event data</summary><code>{JSON.stringify(event.metadata_json)}</code></details></article>)}</section>}
    <section className="translation-detail-summary"><div><span>Status</span><strong className={`translation-status ${row.verification_status}`}>{row.verification_status === "verified_successful" ? "Verified" : row.verification_status.replaceAll("_", " ")}</strong></div><div><span>Operation</span><strong>{row.operation_type}</strong></div><div><span>Controller</span><strong>{row.controller_name || "Unknown"}</strong></div><div><span>Post</span><strong>{row.post_processor_name || "UNKNOWN"} · {row.post_processor_revision || "Unknown revision"}</strong></div><div><span>External AI</span><strong>Prohibited</strong></div><div><span>Paired Code</span><strong>{String(row.cl_parse_summary_json.cl_record_count ?? 0)} CL · {String(row.gcode_parse_summary_json.gcode_block_count ?? 0)} G-code lines</strong></div><div><span>Validation</span><strong>{row.validation_summary_json.blocking_count || 0} blocking · {row.validation_summary_json.warning_count || 0} advisory</strong><button onClick={() => selectTab("technical-validation")}>View Details</button></div></section>
    <section className="translation-provenance panel"><header><h2>Identity and provenance</h2><span>External AI prohibited</span></header><dl><div><dt>CL SHA-256</dt><dd><code>{row.cl_source_hash}</code></dd></div><div><dt>G-code SHA-256</dt><dd><code>{row.gcode_source_hash}</code></dd></div><div><dt>Source</dt><dd>{row.source_system || "Not recorded"}</dd></div><div><dt>Post revision</dt><dd>{row.post_processor_revision || "Unknown"}</dd></div><div><dt>Provenance</dt><dd>{row.source_provenance || "Not recorded"}</dd></div><div><dt>Verification basis</dt><dd>{row.verification_basis || "Not recorded"}</dd></div></dl></section>
    <section className="translation-ai-consent panel" aria-labelledby="ai-consent-heading"><header><div><h2 id="ai-consent-heading">Legacy AI Consent Metadata</h2><p>This historical field is retained for migration compatibility and local audit traceability only.</p></div><strong>Inactive</strong></header>
      <p className="context-note"><strong>CL/NCL transmission to any AI provider is prohibited regardless of this legacy setting.</strong> Historical pairs remain local evidence for deterministic validation and human review.</p>
      <dl><div><dt>Stored legacy value</dt><dd>{row.ai_processing_allowed ? "Previously enabled" : "Not enabled"}</dd></div><div><dt>Current external AI eligibility</dt><dd>Prohibited</dd></div></dl>
    </section>
    <section className="alignment-workspace"><header><div><h2>Technical Alignment Review</h2><p>Review how CL/NCL records correspond to historical G-code blocks. This is primarily used to curate translation evidence.</p></div><button className="button primary" disabled={busy || final} onClick={() => void generate()}>{alignment ? "Rebuild proposals" : "Generate proposals"}</button></header>
      {!alignment ? <div className="translation-empty"><h3>No alignment yet</h3><p>Generate deterministic heuristic proposals, then confirm or reject each relationship.</p></div> : <><div className="alignment-metrics"><span>{alignment.summary_json.coverage_percent || 0}% CL coverage</span><span>{alignment.summary_json.confirmed || 0} confirmed</span><span>{alignment.summary_json.proposed || 0} proposed</span><span>{alignment.summary_json.unmatched_gcode || 0} unmatched G-code</span></div><div className="alignment-grid"><section><header>Creo CL/NCL</header>{row.parsed_cl_records_json.map((record, index) => <button key={index} onClick={()=>selectSource("cl",index)} className={selected?.cl_record_start != null && index >= selected.cl_record_start && index <= (selected.cl_record_end ?? selected.cl_record_start) ? "selected" : ""}><span>{index + 1}</span><code>{String(record.text)}</code></button>)}</section><section className="alignment-links"><header>Relationships</header>{alignment.links.map((link) => <button key={link.id} className={`${link.review_status} ${selected?.id === link.id ? "selected" : ""}`} onClick={() => selectAlignment(link)}><strong>{link.link_type.replaceAll("_", " ")}</strong><span>{Math.round(link.confidence * 100)}%</span><small>{link.review_status}</small></button>)}</section><section><header>Historical G-code</header>{row.parsed_gcode_blocks_json.map((block, index) => <button key={index} onClick={()=>selectSource("gcode",index)} className={selected?.gcode_block_start != null && index >= selected.gcode_block_start && index <= (selected.gcode_block_end ?? selected.gcode_block_start) ? "selected" : ""}><span>{index + 1}</span><code>{String(block.text)}</code></button>)}</section></div>{selected && <aside className="alignment-review"><div><h3>Selected relationship</h3><pre>{spanText(row.parsed_cl_records_json, selected.cl_record_start, selected.cl_record_end)}</pre><span>maps to</span><pre>{spanText(row.parsed_gcode_blocks_json, selected.gcode_block_start, selected.gcode_block_end)}</pre><p>{selected.match_reasons_json.join(" · ")}</p></div><div><button disabled={final} onClick={() => void reviewLink(selected, "reject")}>Reject</button><button className="button primary" disabled={final} onClick={() => void reviewLink(selected, "confirm")}>Confirm</button></div></aside>}</>}
    </section>
    <section className="translation-governance panel"><header><h2>Verification workflow</h2><p>Candidate → reviewed → verified successful. Final records are immutable; verified records may only be deprecated.</p></header><div className="form-grid"><label>Verification reviewer label<input value={reviewer} onChange={(e) => setReviewer(e.target.value)} disabled={final} /></label><label className="full-width">Review note<textarea value={note} onChange={(e) => setNote(e.target.value)} disabled={final && row.verification_status !== "verified_successful"} /></label>{row.verification_status === "reviewed" && <label className="checkbox-label full-width"><input type="checkbox" checked={ack} onChange={(e) => setAck(e.target.checked)} />I acknowledge this verifies a historical translation pair only and does not authorize machine use.</label>}</div><footer>{row.verification_status === "candidate" && <><button disabled={busy || !note || !reviewer} onClick={() => void transition("invalidate")}>Mark invalid</button><button className="button primary" disabled={busy || !note || !reviewer} onClick={() => void transition("review")}>Complete review</button></>}{row.verification_status === "reviewed" && <><button disabled={busy || !note || !reviewer} onClick={() => void transition("invalidate")}>Mark invalid</button><button className="button primary" disabled={busy || !note || !reviewer || !ack} onClick={() => void transition("verify")}>Verify historical pair</button></>}{row.verification_status === "verified_successful" && <button disabled={busy || !note || !reviewer} onClick={() => void transition("deprecate")}>Deprecate verified example</button>}</footer></section>
  </section>;
}
