import { useEffect, useMemo, useRef, useState } from "react";
import type { ToolpathPoint, ToolpathResponse, ToolpathSegment } from "../../types";
import "./toolpath.css";

type View = "XY" | "XZ" | "YZ";
const axes: Record<View, [keyof ToolpathPoint, keyof ToolpathPoint]> = { XY: ["x", "y"], XZ: ["z", "x"], YZ: ["y", "z"] };
function labelPoint(value: ToolpathPoint | null) { return value ? `X${value.x ?? "—"} Y${value.y ?? "—"} Z${value.z ?? "—"}` : "—"; }

export function ToolpathViewer({ data, selectedSegmentId, onSegmentSelect, selectedFindingId }: { data: ToolpathResponse; selectedSegmentId?: string | null; onSegmentSelect?: (segment: ToolpathSegment) => void; selectedFindingId?: number | null }) {
  const canvas = useRef<HTMLCanvasElement>(null); const [view, setView] = useState<View>(data.default_view); const [scale, setScale] = useState(1);
  const [layers, setLayers] = useState({ cl: true, gcode: true, rapid: true, feed: true, findings: true, alignment: true });
  const [tool, setTool] = useState("all"); const [motion, setMotion] = useState("all"); const [operation, setOperation] = useState("all"); const [selected, setSelected] = useState<string | null>(selectedSegmentId ?? null); const [legend, setLegend] = useState(true);
  useEffect(() => { if (selectedSegmentId !== undefined) setSelected(selectedSegmentId); }, [selectedSegmentId]);
  const tools = useMemo(() => [...new Set(data.segments.map((s) => s.tool_number).filter((v): v is number => v != null))], [data]);
  const operations = useMemo(() => [...new Set(data.segments.map((s) => s.operation_id).filter((v): v is string => Boolean(v)))], [data]);
  const visible = useMemo(() => data.segments.filter((s) => layers[s.source_type] && (s.motion_type !== "rapid" || layers.rapid) && (!["linear","arc_cw","arc_ccw"].includes(s.motion_type) || layers.feed) && (tool === "all" || String(s.tool_number) === tool) && (operation === "all" || s.operation_id === operation) && (motion === "all" || motion === "arc" ? motion === "all" || s.motion_type.startsWith("arc") : s.motion_type === motion)), [data, layers, tool, operation, motion]);
  const drawable = useMemo(() => { if (visible.length <= 10000) return visible; const retained = visible.filter((s, i) => i === 0 || i === visible.length-1 || i%Math.ceil(visible.length/8000)===0 || s.finding_ids.length || s.motion_type.startsWith("arc") || s.motion_type === "tool_change"); return retained; }, [visible]);
  useEffect(() => {
    const node=canvas.current; if(!node)return; const ratio=window.devicePixelRatio||1; const width=node.clientWidth||900,height=node.clientHeight||520; node.width=width*ratio;node.height=height*ratio;const ctx=node.getContext("2d");if(!ctx)return;const styles=getComputedStyle(node);const color=(token:string,fallback:string)=>styles.getPropertyValue(token).trim()||fallback;ctx.scale(ratio,ratio);ctx.clearRect(0,0,width,height);ctx.fillStyle=color("--surface","#f8faf8");ctx.fillRect(0,0,width,height);
    const [hAxis,vAxis]=axes[view]; const points=drawable.flatMap(s=>[s.start_point,s.end_point,...s.path_points]).filter((p):p is ToolpathPoint=>Boolean(p)); const hv=points.map(p=>[Number(p[hAxis]??0),Number(p[vAxis]??0)]); if(!hv.length)return; const minH=Math.min(...hv.map(p=>p[0])),maxH=Math.max(...hv.map(p=>p[0])),minV=Math.min(...hv.map(p=>p[1])),maxV=Math.max(...hv.map(p=>p[1])); const margin=30;const fit=Math.min((width-2*margin)/Math.max(1e-6,maxH-minH),(height-2*margin)/Math.max(1e-6,maxV-minV))*scale;const project=(p:ToolpathPoint)=>[margin+(Number(p[hAxis]??0)-minH)*fit,height-margin-(Number(p[vAxis]??0)-minV)*fit] as const;
    ctx.strokeStyle=color("--steel","#bdc8bf");ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(margin,height-margin);ctx.lineTo(width-margin,height-margin);ctx.moveTo(margin,margin);ctx.lineTo(margin,height-margin);ctx.stroke();
    const linked=new Set(data.segments.find(s=>s.id===selected)?.aligned_segment_ids??[]);
    for(const segment of drawable){if(!segment.visualizable||!segment.start_point||!segment.end_point)continue;const active=segment.id===selected||(layers.alignment&&linked.has(segment.id))||segment.finding_ids.includes(selectedFindingId??-1);const pts=segment.path_points.length?segment.path_points:[segment.start_point,segment.end_point];ctx.beginPath();pts.forEach((p,i)=>{const [x,y]=project(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=active?color("--toolpath-selected","#f2a900"):segment.finding_ids.length&&layers.findings?color("--toolpath-blocking","#b4323f"):segment.unmatched?color("--toolpath-unmatched","#72548f"):segment.source_type==="cl"?color("--toolpath-cl","#237a57"):segment.motion_type.startsWith("arc")?color("--toolpath-arc","#2772a7"):segment.motion_type==="rapid"?color("--toolpath-rapid","#63757f"):color("--toolpath-gcode","#334b5d");ctx.lineWidth=active?4:segment.source_type==="cl"?2.5:2;ctx.setLineDash(segment.motion_type==="rapid"?[7,5]:segment.unmatched?[2,4]:[]);ctx.stroke();ctx.setLineDash([]);if(segment.finding_ids.length&&layers.findings){const [x,y]=project(segment.end_point);ctx.fillStyle=color("--toolpath-blocking","#b4323f");ctx.beginPath();ctx.moveTo(x,y-7);ctx.lineTo(x+7,y+6);ctx.lineTo(x-7,y+6);ctx.closePath();ctx.fill()}}
  }, [drawable, view, scale, selected, selectedFindingId, layers.findings]);
  function selectStep(delta:number){const index=Math.max(0,visible.findIndex(s=>s.id===selected));const next=visible[Math.min(visible.length-1,Math.max(0,index+delta))];if(next){setSelected(next.id);onSegmentSelect?.(next)}}
  const selectedSegment=data.segments.find(s=>s.id===selected)??null;
  return <section className="toolpath-viewer"><aside className="toolpath-warning" role="note"><strong>TOOLPATH VISUALIZATION ONLY</strong><span>This view represents parsed programmed motion. It does not model stock removal, fixtures, cutter/holder geometry, collisions, controller look-ahead, machine dynamics, or final part geometry.</span></aside>
    <div className="toolpath-toolbar"><label>View<select aria-label="Toolpath view" value={view} onChange={e=>setView(e.target.value as View)}><option>XY</option><option>XZ</option><option>YZ</option></select></label><fieldset><legend>Layers</legend>{(["cl","gcode","rapid","feed","findings","alignment"] as const).map(key=><label key={key}><input type="checkbox" checked={layers[key]} onChange={e=>setLayers({...layers,[key]:e.target.checked})}/>{key}</label>)}</fieldset><button onClick={()=>setScale(1)}>Fit</button><button onClick={()=>setScale(1)}>Reset</button><button aria-label="Zoom In" onClick={()=>setScale(s=>s*1.2)}>+</button><button aria-label="Zoom Out" onClick={()=>setScale(s=>s/1.2)}>−</button></div>
    <div className="toolpath-filters"><label>Tool<select value={tool} onChange={e=>setTool(e.target.value)}><option value="all">All Tools</option>{tools.map(t=><option key={t} value={t}>T{t}</option>)}</select></label><label>Motion<select value={motion} onChange={e=>setMotion(e.target.value)}><option value="all">All</option><option value="rapid">Rapid</option><option value="linear">Feed</option><option value="arc">Arc</option><option value="cycle">Cycle</option></select></label><label>Operation<select value={operation} onChange={e=>setOperation(e.target.value)}><option value="all">All operations</option>{operations.map(o=><option key={o}>{o}</option>)}</select></label><button onClick={()=>setLegend(!legend)}>{legend?"Hide":"Show"} legend</button></div>
    {legend&&<div className="toolpath-legend"><span className="rapid">Rapid</span><span className="feed">Feed</span><span className="arc">Arc</span><span className="cl">CL</span><span className="gcode">G-code</span><span className="finding">Finding</span><span className="unmatched">Unmatched</span></div>}
    <div className="toolpath-canvas-wrap"><canvas ref={canvas} aria-label={`${view} programmed toolpath visualization`} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();const ratio=(e.clientX-rect.left)/rect.width;const next=visible[Math.min(visible.length-1,Math.floor(ratio*visible.length))];if(next){setSelected(next.id);onSegmentSelect?.(next)}}}/>{data.summary.visualization_simplified&&<span className="toolpath-simplified">Visualization simplified for performance</span>}</div>
    <div className="toolpath-sequence"><button onClick={()=>selectStep(-1)}>Previous</button><input aria-label="Sequence scrubber" type="range" min="0" max={Math.max(0,visible.length-1)} value={Math.max(0,visible.findIndex(s=>s.id===selected))} onChange={e=>{const next=visible[Number(e.target.value)];if(next){setSelected(next.id);onSegmentSelect?.(next)}}}/><button onClick={()=>selectStep(1)}>Next</button></div>
    <div className="toolpath-bottom"><div><dl className="toolpath-summary">{["segments","rapid","feed","arcs","tools","operations","unresolved_geometry"].map(key=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd>{String(data.summary[key]??0)}</dd></div>)}</dl>{data.comparison_summary&&<dl className="toolpath-comparison" aria-label="Visual translation comparison">{Object.entries(data.comparison_summary).map(([key,value])=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd>{String(value)}</dd></div>)}</dl>}</div>{selectedSegment&&<aside className="toolpath-detail"><h3>Segment {selectedSegment.sequence_index+1}</h3><p>{selectedSegment.source_type.toUpperCase()} · Line {selectedSegment.source_line_start} · {selectedSegment.motion_type}</p><code>{labelPoint(selectedSegment.start_point)} → {labelPoint(selectedSegment.end_point)}</code><small>Tool {selectedSegment.tool_number??"—"} · Feed {selectedSegment.feed_rate??"—"} · Spindle {selectedSegment.spindle_speed??"—"} · Plane {selectedSegment.plane??"—"} · Operation {selectedSegment.operation_id??"—"} · Alignment {selectedSegment.alignment_link_id??"unmatched"} · Findings {selectedSegment.finding_ids.join(", ")||"—"}</small></aside>}</div>
    {data.warnings.length>0&&<ul className="toolpath-warnings">{data.warnings.map((w,i)=><li key={`${w.code}-${i}`}><strong>{w.code.replaceAll("_"," ")}</strong> {w.message}</li>)}</ul>}
    <details className="toolpath-table"><summary>Accessible segment table ({visible.length})</summary><table aria-label="Toolpath segments"><thead><tr><th>Sequence</th><th>Motion</th><th>Start</th><th>End</th><th>Tool</th><th>Source line</th><th>Finding</th></tr></thead><tbody>{visible.slice(0,500).map(s=><tr key={s.id} className={s.id===selected?"selected":""} onClick={()=>{setSelected(s.id);onSegmentSelect?.(s)}}><td>{s.sequence_index+1}</td><td>{s.motion_type}</td><td>{labelPoint(s.start_point)}</td><td>{labelPoint(s.end_point)}</td><td>{s.tool_number??"—"}</td><td>{s.source_type} {s.source_line_start}</td><td>{s.finding_ids.join(", ")||"—"}</td></tr>)}</tbody></table>{visible.length>500&&<p>First 500 rows shown; all segments remain available on the canvas and through sequence controls.</p>}</details>
  </section>;
}
