import { fireEvent, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { expect, test, vi } from "vitest";
import { ToolpathViewer } from "./ToolpathViewer";
import type { ToolpathResponse } from "../../types";

const data: ToolpathResponse = { source:"both",machine_type:"lathe",default_view:"XZ",coordinate_context:"work",bounds:{min_x:0,max_x:2,min_y:0,max_y:0,min_z:-1,max_z:1},summary:{segments:3,rapid:1,feed:1,arcs:1,tools:1,operations:1,unresolved_geometry:0,visualization_simplified:false},warnings:[{code:"DIAMETER_RADIUS_MODE_UNKNOWN",message:"Raw programmed X values are shown."}],comparison_summary:{aligned_motion_pairs:1,matching_geometry:1},advisory_only:true,safety_notice:"TOOLPATH VISUALIZATION ONLY",segments:[
  {id:"cl-1",source_type:"cl",source_record_id:1,source_line_start:2,source_line_end:2,operation_id:"Facing",tool_number:1,motion_type:"rapid",start_point:{x:0,y:0,z:0},end_point:{x:2,y:0,z:1},center_point:null,radius:null,path_points:[],plane:null,feed_rate:null,spindle_speed:900,rapid:true,arc_direction:null,helical:false,tool_axis:null,alignment_link_id:8,aligned_segment_ids:["gcode-1"],finding_ids:[],sequence_index:0,visualizable:true,unmatched:false,geometry_status:"matching_geometry",metadata_json:{}},
  {id:"gcode-1",source_type:"gcode",source_record_id:1,source_line_start:3,source_line_end:3,operation_id:"Facing",tool_number:1,motion_type:"linear",start_point:{x:0,y:0,z:0},end_point:{x:2,y:0,z:1},center_point:null,radius:null,path_points:[],plane:"G18",feed_rate:8,spindle_speed:900,rapid:false,arc_direction:null,helical:false,tool_axis:null,alignment_link_id:8,aligned_segment_ids:["cl-1"],finding_ids:[4],sequence_index:1,visualizable:true,unmatched:false,geometry_status:null,metadata_json:{}},
  {id:"gcode-2",source_type:"gcode",source_record_id:2,source_line_start:4,source_line_end:4,operation_id:"Facing",tool_number:1,motion_type:"arc_cw",start_point:{x:2,y:0,z:1},end_point:{x:1,y:0,z:-1},center_point:{x:1,y:0,z:1},radius:1,path_points:[{x:2,y:0,z:1},{x:1,y:0,z:-1}],plane:"G18",feed_rate:8,spindle_speed:900,rapid:false,arc_direction:"cw",helical:false,tool_axis:null,alignment_link_id:null,aligned_segment_ids:[],finding_ids:[],sequence_index:2,visualizable:true,unmatched:true,geometry_status:null,metadata_json:{}}
]};

test("viewer provides technical controls, warnings, legend, table, and selection", async()=>{const user=userEvent.setup();const selected=vi.fn();render(<ToolpathViewer data={data} onSegmentSelect={selected}/>);expect(screen.getByText("TOOLPATH VISUALIZATION ONLY")).toBeInTheDocument();expect(screen.getByLabelText("Toolpath view")).toHaveValue("XZ");await user.selectOptions(screen.getByLabelText("Toolpath view"),"XY");expect(screen.getByLabelText("Toolpath view")).toHaveValue("XY");expect(screen.getAllByText("Rapid").length).toBeGreaterThan(0);expect(screen.getByText(/DIAMETER RADIUS MODE UNKNOWN/)).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Next"}));expect(selected).toHaveBeenCalled();expect(screen.getByText(/Accessible segment table/)).toBeInTheDocument();});
test("layer, tool, operation, motion, zoom, fit, and reset controls remain interactive",async()=>{const user=userEvent.setup();render(<ToolpathViewer data={data}/>);await user.click(screen.getByLabelText("cl"));await user.selectOptions(screen.getByLabelText("Tool"),"1");await user.selectOptions(screen.getByLabelText("Motion"),"Arc");await user.selectOptions(screen.getByLabelText("Operation"),"Facing");await user.click(screen.getByRole("button",{name:"Zoom In"}));await user.click(screen.getByRole("button",{name:"Zoom Out"}));await user.click(screen.getByRole("button",{name:"Fit"}));await user.click(screen.getByRole("button",{name:"Reset"}));fireEvent.click(screen.getByLabelText(/programmed toolpath visualization/),{clientX:20,clientY:20});expect(screen.getAllByText(/Segment/).length).toBeGreaterThan(0);});
